version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-oracle.properties
    image: conductor:server
    container_name: conductor-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
      args:
        YARN_OPTS: ${YARN_OPTS}
    networks:
      - internal
    ports:
      - 8080:8080
      - 5000:5000
    healthcheck:
      test: [ "CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - conductor-oracle:oracle
    depends_on:
      conductor-oracle:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    volumes:
      - ./server/config/config-oracle.properties:/app/config/config-oracle.properties:ro

  conductor-oracle:
    image: gvenzl/oracle-xe:21.3.0-slim
    environment:
      - ORACLE_PASSWORD=conductor
      - ORACLE_DATABASE=conductor
      - APP_USER=conductor
      - APP_USER_PASSWORD=conductor
    volumes:
      - oracle-conductor:/opt/oracle/oradata
    networks:
      - internal
    ports:
      - 1521:1521
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/1521'
      interval: 60s
      timeout: 30s
      start_period: 180s
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  oracle-conductor:
    driver: local

networks:
  internal: